export const SETUSERINFO = "SETUSERINFO";
export const SETANIMATE = "SETANIMATE";
export const SETOTP = "SETOTP";
export const SETLOGIN = "SETLOGIN";
export const SETLOGINERROR = "SETLOGINERROR";
export const CLEARUSERDATA = "CLEARUSERDATA";
