export const SETASSESSMENTDATA = "SETASSESSMENTDATA";
export const SETRESPONSE = "SETRESPONSE";
export const SETATTEMPTLATER = "SETATTEMPTLATER";
export const SETRESULT = "SETRESULT";
export const UPDATERESULT = "UPDATERESULT";
export const SETSHOWANSWERS = "SETSHOWANSWERS";
export const CLEARDATA = "CLEARDATA";
export const SKIPASSESSMENT = "SKIPASSESSMENT";
